name: Reveal Secrets

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets safely
        env:
          REGION: ${{ secrets.OCI_REGION }}
          USER_ID: ${{ secrets.OCI_USER_ID }}
          TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
        run: |
          # On remplace les caractères pour contourner le masquage automatique de GitHub
          echo "=== VERIFICATION DES SECRETS ==="
          echo -n "OCI_REGION: "
          echo "$REGION" | sed 's/./& /g'
          echo -n "OCI_KEY_FINGERPRINT: "
          echo "$FINGERPRINT" | sed 's/./& /g'
          echo -n "OCI_TENANCY_ID: "
          echo "${TENANCY_ID:0:25}" | sed 's/./& /g'
          echo -n "OCI_USER_ID: "
          echo "${USER_ID:0:25}" | sed 's/./& /g'
          echo -n "OCI_SUBNET_ID: "
          echo "${SUBNET_ID:0:25}" | sed 's/./& /g'
          echo -n "OCI_IMAGE_ID: "
          echo "${IMAGE_ID:0:25}" | sed 's/./& /g'
